Add Module controller
kubeform/module pull request #2
Opened 2022-02-16 06:39 UTC by shahincsejnu

2022-02-16 17:58 UTC, faem requested changes

2022-02-16 17:58 UTC, faem commented on controllers/util.go
> +	hostName := sourceSlice[0]
use url.Parse()

2022-02-16 17:58 UTC, faem commented on controllers/util.go
> +	err = generateOutputTFFile(outputFile, moduleName, jsnSchemaPropsForOutput)
handle error

2022-02-16 17:58 UTC, faem commented on controllers/util.go
> +	}
We don't want clone in every reconciliation, if the repo already exists, use that directly.

2022-02-16 17:58 UTC, faem commented on controllers/util.go
> +	//}
delete

2022-02-16 17:58 UTC, faem commented on Dockerfile
> +#USER 65532:65532
delete

2022-02-16 17:58 UTC, faem commented on Dockerfile
> +FROM ubuntu:latest
ubuntu:20.04

2022-02-28 03:44 UTC, shahincsejnu commented on controllers/util.go
> +	}
Done

2022-03-03 06:50 UTC, faem approved these changes

2022-03-03 06:50 UTC, merged